import { StyleSheet } from "react-native"

export const createExchangeStyles = (isDark: boolean) => {
  const colors = isDark
    ? {
        bg: "#0F111A",
        card: "#181823",
        text: "#fff",
        textSecondary: "#A1A1B5",
        border: "#2E2E3D",
        accent: "#818CF8",
        accentLight: "#312E81",
        rate: "#A5B4FC",
      }
    : {
        bg: "#f9f9f9",
        card: "#fff",
        text: "#000",
        textSecondary: "#374151",
        border: "#E5E7EB",
        accent: "#3B82F6",
        accentLight: "#EFF6FF",
        rate: "#10B981",
      }

  return StyleSheet.create({
    container: {
      flex: 1,
      paddingHorizontal: 24,
      paddingVertical: 32,
      backgroundColor: colors.bg,
    },
    loadingContainer: {
      flex: 1,
      backgroundColor: colors.bg,
    },
    loadingCenter: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingText: {
      marginTop: 16,
      fontSize: 16,
      color: colors.textSecondary,
    },
    header: {
      alignItems: "center",
      marginBottom: 28,
    },
    logo: {
      width: 70,
      height: 70,
      resizeMode: "contain",
      marginBottom: 8,
    },
    title: {
      fontSize: 26,
      fontWeight: "700",
      textAlign: "center",
      color: isDark ? "#E5E7EB" : "#111827",
    },
    label: {
      fontSize: 15,
      fontWeight: "500",
      marginBottom: 6,
      marginTop: 8,
      color: colors.textSecondary,
    },
    inputBox: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 12,
      paddingHorizontal: 16,
      marginBottom: 12,
      borderColor: colors.border,
      backgroundColor: colors.card,
    },
    selected: {
      fontSize: 16,
      fontWeight: "500",
      color: colors.text,
    },
    list: {
      position: "absolute",
      left: 0,
      right: 0,
      height: 300,
      borderWidth: 1,
      borderRadius: 14,
      borderColor: colors.border,
      backgroundColor: colors.card,
      shadowColor: "#000",
      shadowOpacity: 0.12,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
      elevation: 8,
      zIndex: 20,
    },
    overlay: {
      position: "absolute",
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      zIndex: 10,
    },
    item: {
      flexDirection: "row",
      alignItems: "center",
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderBottomWidth: 1,
      borderBottomColor: isDark ? "#2D2D3A" : "#F3F4F6",
      color: isDark ? "#E0E0E6" : "#111",
    },
    itemText: {
      fontSize: 15,
      color: isDark ? "#E0E0E6" : "#111",
    },
    rateBox: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "center",
      gap: 8,
      marginTop: 24,
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: 12,
      backgroundColor: isDark ? "#1E1E2F" : "#EFF6FF",
    },
    rateText: {
      fontSize: 16,
      fontWeight: "600",
      color: colors.rate,
    },
    amount: {
      borderWidth: 1,
      borderRadius: 12,
      paddingVertical: 15,
      paddingHorizontal: 16,
      fontSize: 16,
      marginTop: 30,
      borderColor: colors.border,
      backgroundColor: colors.card,
      color: colors.text,
    },
    resultCard: {
      marginTop: 28,
      borderRadius: 16,
      paddingVertical: 20,
      paddingHorizontal: 24,
      shadowColor: "#000",
      shadowOpacity: 0.15,
      shadowRadius: 10,
      shadowOffset: { width: 0, height: 6 },
      elevation: 6,
    },
    resultText: {
      fontSize: 20,
      fontWeight: "700",
      color: "#fff",
      textAlign: "center",
      letterSpacing: 0.5,
    },
  })
}
